version: '3.9'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - laravel_net
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_DATABASE: job_portal
      MYSQL_USER: jeremie
      MYSQL_PASSWORD: jeremie
      MYSQL_ROOT_PASSWORD: jeremie
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_net

networks:
  laravel_net:

volumes:
  db_data:
